### ISSUE TITLE
您好，这个怎么回事呢

### ISSUE THREAD

**Issue by xa-yifan** [GavinGuan24/ahri#10]
2021-06-09 18:01:28.175 Crash - listen tcp 58.215.87.40:5555: bind: cannot assign requested address
core.NewAhriServer(0x7ffe0e87f651, 0xd, 0x7ffe0e87f662, 0x4, 0x7ffe0e87f66a, 0x6, 0x7ffe0e87f674, 0x13, 0x7ffe0e87f68b, 0x12, ...)
	/usr/local/go/src/core/ahriServer.go:314 +0x522
main.main()
	/root/go/ahri/product/server/server.go:66 +0x625

**Comment by GavinGuan24** [comment]
正如报错的内容，系统无法分配这个 socket(58.215.87.40:5555)给 ahri 使用。
你的系统可能已经占用了这个 socket，或者有其他安全机制不允许 ahri 监听这个 socket
