### ISSUE TITLE
老哥，Ahri 还是启动不起来

### ISSUE THREAD

**Issue by xa-yifan** [GavinGuan24/ahri#12]
老哥，Ahri 还是启动不起来，[#10 ](https://github.com/GavinGuan24/ahri/issues/10#issue-916022531)不是端口占用问题，Ahri这个项目我很需要，谢谢老哥

**Comment by xa-yifan** [comment]
![image](https://user-images.githubusercontent.com/61110064/128896520-dd0819c6-df2e-496e-b36c-d14139ace9af.png)

**Comment by GavinGuan24** [comment]
嗯，你看报错信息，在项目的 core/ahriServer.go:314
的确是 tcp 地址bind 时报的错。
你这个机子要么是有安全软件，要么是端口已经被占用了。
总之就是用不了。这种问题和 ahri 源码无关，我帮不了你。

建议是，你找找原因，是什么东西阻止了软件使用这个 139.9.140.172:3547 地址。
百度上 139.9.140.172  被识别为 华为云的 IP，我猜是华为云有一些安全策略，你应该问问客服。
我之前使用阿里云也有类似的经历。

还有，如果你仅仅是为了FQ，你应该买国外的 VPS，然后使用 SpreadX。
详情见本项目的 release。

**Comment by xa-yifan** [comment]
老哥，我不是为了FQ。
我把服务端的-ip改成0.0.0.0 可以成功启动，但是现在存在以下问题，不知道是我配置不对还是。
首先 服务端启动信息及日志如下
![image](https://user-images.githubusercontent.com/61110064/129340718-fd5b4286-f492-4651-8ad9-16973925052a.png)


客户端B(1: Give)
![image](https://user-images.githubusercontent.com/61110064/129339453-46b04852-14f9-42a2-b837-47300bdf04d5.png)

客户端A(0: Take) 启动命令及日志截图
![image](https://user-images.githubusercontent.com/61110064/129339664-836a5348-fadc-489a-ae67-780e0ded6f59.png)

客户端A ahri.hosts 只配置了 [ 192.168.1.224 B ] ，意思访问192,168.1.224 会通过服务端去转发到客户端B

本机代理如下
![image](https://user-images.githubusercontent.com/61110064/129340002-fab2c448-c19a-4e0a-917d-7707a889cab3.png)


**但是现在访问不通192.168.1.224**
不知道我配置的对吗？麻烦老哥了

**Comment by GavinGuan24** [comment]
恩，你用的华为云的VPS，0.0.0.0 帮你成功启动了 ahriServer。恭喜你。
因为国内云厂商的 VPS 通常有好几个网卡，不论是真实还是虚拟网卡。还有一些安全策略。总之，你成功地启动了 ahriServer 。
这是第一步。

你应该详细看过我写的教程。看你截图的日志，客户端 A 和 B 都已经成功地注册到 ahriServer。
这是第二步。

按你说的 ahri.hosts 你也配置好了。
这是第三步。

可是最后一步，你win配置socks5。
因为我平常几乎不用win。我只是百度了一下。
你这个win配置本地 socks5 貌似不对啊。
这样会导致，你的网络流量都没到 Ahri 的本地 socks5 server。
等于你房子都买好，也装修了，但是没开门的钥匙。

恩，我没 win 电脑可以测试，你可以百度 “win10 配置socks5”

我百度了一下，你看看这个能不能帮你完成 win 的本地 socks5 配置。
[![fRK2LQ.png](https://z3.ax1x.com/2021/08/16/fRK2LQ.png)](https://imgtu.com/i/fRK2LQ)
[博客](https://www.cnblogs.com/xuyaowen/p/socks5-on-windows10.html)

**Comment by GavinGuan24** [comment]
随便一提，毕竟好久不用这个工具了，我抽空看了一下源码，当时设计 ahri.hosts 时，是 IP 和域名都支持的。

**Comment by xa-yifan** [comment]
感谢大哥，不过我用frp+openvpn实现了

**Comment by xa-yifan** [comment]
不过你这个项目很简洁，很棒，go能做的事情很多吗？

**Comment by GavinGuan24** [comment]
除了不能写操作系统，其他领域都行。毕竟没有人会用一个自带GC的语言写操作系统。
