### ISSUE TITLE
编译服务器端遇错

### ISSUE THREAD

**Issue by luckypoem** [GavinGuan24/ahri#2]
hi.

[root@hs gopath]# go get -u -v github.com/GavinGuan24/ahri/product/server/
github.com/GavinGuan24/ahri (download)
github.com/GavinGuan24/ahri/core
# github.com/GavinGuan24/ahri/core
src/github.com/GavinGuan24/ahri/core/utils.go:58:10: undefined: strings.ReplaceAll
[root@hs gopath]#

怎么解决？

**Comment by GavinGuan24** [comment]
首先, release 中有编译好的二进制文件, 你可以直接用.

其次,
我印象中, go 11 之后才有比较完善各种官方工具包.
我在 go version go1.12.1 darwin/amd64 环境编写的 Ahri.
所以, 你可以升级自己的 go 到 1.12.1 + 来解决这个问题.

**Comment by briteming** [comment]
我升级自己的 go版本 到go 1.13，解决了这个问题
