### ISSUE TITLE
是否支持多个服务器负载均衡？

### ISSUE THREAD

**Issue by toplinuxsir** [GavinGuan24/ahri#3]
是否支持多个服务器负载均衡？

**Comment by GavinGuan24** [comment]
能不能说明一下你想的架构是什么样的 ？ 
需要在什么位置架设 LB ？

**Comment by GavinGuan24** [comment]
如果你的意思是，使用多个 ahri-server。那么一定需要同样数量的 ahri-client。再将数个 ahri-client 视为一个集合，在它们前面架设 LB。

因为，Ahri 的最简模型是 Client <=====> Server，它们之间仅保留一条 TCP 连接。

**Comment by toplinuxsir** [comment]
@GavinGuan24  一个client ,自动分发流量到多个Ahri-server

**Comment by GavinGuan24** [comment]
可以做到，源码是组件化的，少量改动即可实现。但我想不出这样做的应用场景。你实际场景是什么呢 ？
