### ISSUE TITLE
使用帮助

### ISSUE THREAD

**Issue by ghost** [GavinGuan24/ahri#4]
不好意思，你的文档没有看的很明白，能不能给个在windows上使用的例子，比如，我只是想在家的时候可以远程公司的电脑，那么我在公司的电脑需要ahri-server，家里的电脑ahri-client，反过来我如果在公司的电脑想远程家里的电脑，需要家里ahri-server，公司的电脑ahri-client吗？不好意思，对于vpn这块是个小白，请指教一下

**Comment by GavinGuan24** [comment]
文档写的不够通俗易懂是我的锅，我会考虑近期更新一版 readme 的。

你的留言中出现了 “远程” 一词，我不确定你是需要 VPN 还是远程控制。如果情况是后者，teamviewer 个人版是免费的，你大可使用，ta 是最好的，没有之一。

如果是需要 VPN，你需要清楚，国内的网络供应商提供的民用网络环境均是内网 IP。

所以，根据网络方面的基础知识，任何人想做到【💻(家) --访问--> 💻(公司)】，或者反过来，都是需要一个具有公网 IP 的机器来转发数据的。

ahri-server 运行在具有公网 IP 的机器上。
ahri-client 运行在任何提供内网服务或需要被服务的机器上。

Ahri 支持理论上支持所有基于 TCP 的应用层协议。如果你用 VPN 是为了访问内网的网页等资源，Ahri 能帮到你，如果你是想用 ssh，我建议你直接使用 openssh 内置的 socks 代理功能。

如果我说的还是不够清楚，你可以留下自己的联系方式，私聊。

**Comment by feifei88221** [comment]
> 文档写的不够通俗易懂是我的锅，我会考虑近期更新一版 readme 的。
> 
> 你的留言中出现了 “远程” 一词，我不确定你是需要 VPN 还是远程控制。如果情况是后者，teamviewer 个人版是免费的，你大可使用，ta 是最好的，没有之一。
> 
> 如果是需要 VPN，你需要清楚，国内的网络供应商提供的民用网络环境均是内网 IP。
> 
> 所以，根据网络方面的基础知识，任何人想做到【💻(家) --访问--> 💻(公司)】，或者反过来，都是需要一个具有公网 IP 的机器来转发数据的。
> 
> ahri-server 运行在具有公网 IP 的机器上。
> ahri-client 运行在任何提供内网服务或需要被服务的机器上。
> 
> Ahri 支持理论上支持所有基于 TCP 的应

**Comment by ghost** [comment]
是我理解的有问题，我的需求有点偏题，我其实是想要远程控制类的软件，ahri只是用来做vpn的，也就是公网到内网的转换，我可以这么理解吗？arhi是一个工具，可以利用公网来开辟一条连接内网的通道，来达到在公网上访问内网的目的，还有，如果我们在国外有arhi服务器的话，我们就可以利用arhi来翻墙了，不知道理解的对不对？谢谢你的回答，很详细，很耐心，对一个外行来解释这么多，真的很谢谢了，会一直关注项目的。

**Comment by GavinGuan24** [comment]
你的理解完全正确。但我不鼓励将 Ahri 的辅助功能用于蕃嫱。
日常提醒：请严格遵守你所在地区的相关法律法规, 不要将 Ahri 用于违法犯罪行为(😂尤其是科学上网)。
