### ISSUE TITLE
希望有一个教程

### ISSUE THREAD

**Issue by ethanyaol** [GavinGuan24/ahri#5]
您好，可能是本人动手能力比较差，研究了下您的readme，还是没有搞定，可否写一个windows下的小白使用教程？谢谢

**Comment by GavinGuan24** [comment]
好, 可以的.

**Comment by GavinGuan24** [comment]
https://github.com/GavinGuan24/ahri/blob/master/core/ahri_guide.md

命令行懂得自然懂，不懂的，我也不能写的太详细，自己百度吧。

总之，
如果你在家使用公司内网，流程是这样的 
```
A(家里电脑) -> S(公网服务器) -> B(公司电脑) -> 内网
```

如果你访问 Google，流程是这样的 
```
A(家里电脑) -> S(公网服务器) -> Google
```
