### ISSUE TITLE
如何强制代理所有的URL ？

### ISSUE THREAD

**Issue by toplinuxsir** [GavinGuan24/ahri#6]
如何强制代理所有的URL 都走S ？
而不是每次都得增加一个？ 支持*通配符？

**Comment by GavinGuan24** [comment]
Ahri 主功能是为了不影响本地网络使用的同时，扩展使用数个内网环境。
我不希望为了辅助功能而阻碍主功能的使用。所以，我不会主动修改源码。

但，如果你仅希望使用辅助功能，且所有流量转发到 S。
你可以 fork 之后自行修改。

我给你两个方案，你自己斟酌。

# 方案一

https://github.com/GavinGuan24/ahri/blob/master/core/ahriSocks5Server.go 

101 ~ 105 行，修改为如下

```
func (ahriSocks5Server *AhriSocks5Server) mapperAhriAddrName(atyp byte, byteAddr []byte) string {
	//ahriSocks5Server.addrCtxMapperLock.Lock()
	//defer ahriSocks5Server.addrCtxMapperLock.Unlock()
	//return MapperAhriAddrName(atyp, byteAddr, ahriSocks5Server.addrCtxMapper)
        return "S"
}
```

然后 cd 至项目根目录重新编译即可。
这个快捷脚本可用 ./cross_compile.sh

或者你仅编译你需要的 ahri-client
cd ./product/client && go build -o ahri-client

### 但是你要知道，一旦这样写之后，ahri.hosts 不再对 ahri 生效。且即使是不需要代理的域名，其流量也会被转发到 S（根据你的描述，这应该是你想要的）。

---

# 方案二

ahri-client 启动之后的日志中，基本上只有这样的内容。看 **name**，**dstAddr** 这两个值
```
2019-11-08 20:28:58.242 * - Connect(12) Target AhriAddr(name: L, atyp: 3, dstAddr: h-adashx.ut.taobao.com, port: 443).
2019-11-08 20:29:08.267 * - Connect(13) Target AhriAddr(name: S, atyp: 3, dstAddr: www.google.com, port: 443).
```
你可以很清晰地知道你访问的网站使用了几个**域名**下的资源，从而将你需要的域名添加到 ahri.hosts 中。
所以，痛苦一次，终身受用。因为只有你自己知道最适合你的防火墙名单。

**Comment by toplinuxsir** [comment]
@GavinGuan24  Thanks !
