### ISSUE TITLE
Dalao能不能考虑加个xtcp的功能，这样做可以减少购买公网服务器带宽的成本

### ISSUE THREAD

**Issue by FUjr** [GavinGuan24/ahri#7]
（纯小白，不懂技术

**Comment by GavinGuan24** [comment]
我搜了一下, 
你说的是 [frp](https://github.com/fatedier/frp/blob/master/README_zh.md) 的 xtcp 吧, 网络原理了解一下. 

我说的"公网"是相对的概念, 意思比较广义. 
xtcp 的优化应该是检测到网络链路上, 两个机子在同一个网中, 于是就不走服务器流量.

狭义点说, 这个场景是, 两台机子在同一个内网, 由于一些原因无法直接访问. 
那你本就不需要购买公网服务器.
在那个网络中的每台机子上部署对应的ahri就可以相互dial了.

**Comment by FUjr** [comment]
> 我搜了一下, 
> 你说的是 [frp](https://github.com/fatedier/frp/blob/master/README_zh.md) 的 xtcp 吧, 网络原理了解一下. 
> 
> 我说的"公网"是相对的概念, 意思比较广义. 
> xtcp 的优化应该是检测到网络链路上, 两个机子在同一个网中, 于是就不走服务器流量.
> 
> 狭义点说, 这个场景是, 两台机子在同一个内网, 由于一些原因无法直接访问. 
> 那你本就不需要购买公网服务器.
> 在那个网络中的每台机子上部署对应的ahri就可以相互dial了.


我试了一下，xtcp不是局限于局域网的，它相当于在公网提供服务，为两个在内网的设备建立隧道（如果运营商支持），这样即使是1m带宽的服务器也能完美运行

**Comment by GavinGuan24** [comment]
> > 我搜了一下,
> > 你说的是 [frp](https://github.com/fatedier/frp/blob/master/README_zh.md) 的 xtcp 吧, 网络原理了解一下.
> > 我说的"公网"是相对的概念, 意思比较广义.
> > xtcp 的优化应该是检测到网络链路上, 两个机子在同一个网中, 于是就不走服务器流量.
> > 狭义点说, 这个场景是, 两台机子在同一个内网, 由于一些原因无法直接访问.
> > 那你本就不需要购买公网服务器.
> > 在那个网络中的每台机子上部署对应的ahri就可以相互dial了.
> 
> 我试了一下，xtcp不是局限于局域网的，它相当于在公网提供服务，为两个在内网的设备建立隧道（如果运营商支持），这样即使是1m带宽的服务器也能完美运行

【它相当于在公网提供服务】那就是需要部署在公网IP的机子上啊。
【为两个在内网的设备建立隧道（如果运营商支持）】。什么类型的隧道？VPN？【如果运营商支持】 不花钱？
【1m带宽的服务器】我之前用的就是，没卡过。
