### ISSUE TITLE
sockets代理国内网站正常，代理国外网站乱码网页无法显示，是什么原因？

### ISSUE THREAD

**Issue by ops-cn** [GavinGuan24/ahri#8]
**操作命令：**
$ curl --socks5 127.0.0.1:23456 www.baidu.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2381  100  2381    0     0  74406      0 --:--:-- --:--:-- --:--:-- 74406<!DOCTYPE html>
<html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus></span><span class="bg s_btn_wr"><inputtype=submit id=su value=百度一下 class="bg s_btn"></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=http://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');</script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>

dell@DESKTOP-N0L4O5J MINGW64 ~/Desktop
$ curl --socks5 127.0.0.1:23456 https://www.github.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**日志信息：**

Ahri Client (0.9.3) is running.

2020-11-13 10:33:19.144 Debug - Ignored line in the File(E:\workspace\go\src\ahri\product\client\ahri.hosts: 5).
2020-11-13 10:33:19.154 Debug - Ignored line in the File(E:\workspace\go\src\ahri\product\client\ahri.hosts: 13).
2020-11-13 10:33:19.258 * - Registered to the server successfully.
2020-11-13 10:33:26.792 * - Connect(1) Target AhriAddr(name: L, atyp: 1, dstAddr: 36.152.44.95, port: 80).
2020-11-13 10:33:26.792 Debug - This is already an ipv4 address.
2020-11-13 10:33:26.803 Debug - Connect(1) data: GET / HTTP/1.1
Host: www.baidu.com
User-Agent: curl/7.61.1
Accept: */*

2020-11-13 10:33:26.814 Debug - Connect(1) data: HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 2381
Content-Type: text/html
Date: Fri, 13 Nov 2020 02:33:27 GMT
Etag: "588604f8-94d"
Last-Modified: Mon, 23 Jan 2017 13:28:24 GMT
Pragma: no-cache
Server: bfe/1.0.8.18
Set-Cookie: BDORZ=27315; max-age=86400; domain=.baidu.com; path=/

<!DOCTYPE html>
<html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn"></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=http://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');</script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>

2020-11-13 10:33:26.815 Debug - Connect(1) data read-err: EOF
2020-11-13 10:33:31.816 Debug - Connect(1) data read-err: read tcp 192.168.0.235:62482->36.152.44.95:80: use of closed network connection
2020-11-13 10:33:31.816 Debug - Connect(1) Closed.

===============================================================

2020-11-13 10:33:39.306 * - Connect(2) Target AhriAddr(name: L, atyp: 1, dstAddr: 13.229.188.59, port: 443).
2020-11-13 10:33:39.306 Debug - This is already an ipv4 address.
2020-11-13 10:33:39.453 Debug - Connect(2) data:   �^����t��H�[f[ �iIUn�w�>s����  ��0�,�(�$��
� 
 � 3      www.github.com    
   	 
     3t     hhttp/1.1  �                                                                                                                                                                                 
2020-11-13 10:33:39.526 Debug - Connect(2) data:  l  hC#kc�[��իY���^��$kDOWNGRD (� �o����CQ�v!��#����*�U�/   �            http/1.1� � � �0��0���W�(&��{
 0p10	UUS10U
220510120000Z0f10	UUS10U
San Francisco10U
GitHub, Inc.10U
 � 0�
� �2��؞���y)L+��\Cԓ;�x�0T���/���g�TZ���ք�,�-ND&�7�����Lk&	��YD[������_�_�6ذ�o�"T��)CUR���h{�VQЧ��ZG��<�r�6���,.����IwU��J�ۋ)5g��� �y�`
xs�(u���1�	6���-F�%+v����}�h�;�3^T*ߛ���@��k�=+Ӎ�_�k��u�<&7/1���7���t3�{
�r���k� ��s0�o0U#0�Qh���u<��edb��Yr;0Uc�]_���Z�v6��,�H0%U0�
github.com�www.github.com0U��0U%0++0uUn0l04�2�0�.http://crl3.digicert.com/sha2-ha-server-g6.crl04�2�0�.http://crl4.digicert.com/sha2-ha-server-g6.crl0LU E0C07	`�H��l0*0(+https://www.digicert.com/CPSg�0��+w0u0$+0�http://ocsp.digicert.com0M+0�Ahttp://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA.crt0U�0 0�|
+�y�l�hf u )y��99!�Vs�c�w�W}�`
 � �2������:Dq $��X1̪���ůĻ�_��jB�!�%�k,7�*�n��O�/��:���0���
 0l10	UUS10U
281022120000Z0p10	UUS10U
 � 0�
� ��/�$�m_��
x�{�^q�J�����#M��u�����D5eS%9�
�c�th
 � ����m�\�h�J���Q/�kD��c��nl�����q�[�4N��y�)�-�j�� �y��G����Yq}��k�YX=��1%\8��柂��[�1N�x����I��'��r�>��A��6��nGI^�H|���I��&B@�֒�d
WT���^k��Ā�r�V����0�0�N�W�$��+��u��-�}y'��ꪅ�� (AYC(ҁ���{;w�@b�AE�>��3�g�a.r��i� W@p�ɴM I A����r�k��'z�^�^��g�/��_�v�3C�Ld5,X����S�(��n�D�����[ǝ�o� h�V:V�H�^��`+�r���O�m��
E
�	u���C��X���gK��ӧ��6��hpCLU �" :/H�
�e�i���$m��jopeO[�Q��yS~(�A�v�����/���w��5���SW�S^U�(�20|A^��g�`@	(���F�{7%���jC���
Q��4+:e��t6]�1���`�;�{\��Վ��ϻ�]sʚ�W�����q���    
Z�e,��:  (x�y�r2lGW� P`��Y_6���=�5zq�^Rzտg���F
���~�<_�M�
2020-11-13 10:33:39.601 Debug - Connect(2) data:  fx�y�r2lH|,bԬ]K�5�� �A"��YGOgܻA��[���]-�Y���ࠋ���}� �^!�p�(I���Z�N/�~lq�贵]�zѫִ�,Q/�)p�
ꊚ�)#��5Hl�QΧ�	��ӸQ��G�٦1*{\���ޖ�,�{ "�܈��\H�J
�J
2020-11-13 10:33:39.673 Debug - Connect(2) data:  x�y�r2lIw<ފ���4��a)�[/-v
2020-11-13 10:33:39.674 Debug - Connect(2) data read-err: EOF
2020-11-13 10:33:39.745 Debug - Connect(2) data:  4pk��)#×2��Ŝ�#,�.P
2020-11-13 10:33:39.745 Debug - Connect(2) data read-err: EOF
2020-11-13 10:33:44.745 Debug - Connect(2) Closed.

**Comment by GavinGuan24** [comment]
打印出来的是报文，HTTPS 的报文本就是密文。不乱码，难道我能给你转出明文？╮(╯_╰)╭
